# -*- coding: utf-8 -*-
"""hai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yActi02qyT8gVCDHflDSaPoZSh7uOxMq
"""

print("hello")